sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
install: ''
before_script: ./.travis_release.sh
script:
- sbt publish
env:
  global:
  - secure: XFJBv5e1SmGATbacxgJSjCs2dMyu3uRcrZvLO9oEHHDNY1p+UacIc08AkWFiRA8tbO4r1txUO3uhrLiqK/9QflM3UBBi2+8lGSr52XwM/CwFKUGYzk2c9OQyLYnVxKUDZn4idt51q6iBJ7UpbY4DrpmbIticNsHf7gkIHm2eTpI7rHldVsfi75vDIcoZS/FQy+yErVpqph1MFqFeHsx2qUSKykDlwwVpg6wmcnnwuJ2yZTMFFKWKl6AGnSym21eBrPTy37WbjrfvyvAVv3yqbuyoBOXA9HCzxX9OJ4nmMhgQRBPHVxpaMHThS5SYQACyllePaEZGySkY8T0KlZyqQwk0VgziNphw50zF6eRa6Qcs0xTBMwmvumsa8wrfcGXzHC7HkJwVxeOhTLcZfM8yMBStpff34eDlFSxXymdv9B+gmq4UavuuYAxb9tmlrvVBn3gSywPLn9JVv1Gu5+jABEg2tZfgo98tBpvpDTzKKZ8kbZxnitvc4oLCCnaEjLXPrvGeR3m4hMRHpGp9WzRy00r/3mz96qMUKwAk5y1qW1+fAcbA3TXCqRVdes0JbatGb8ajSu03YpRgeQqT1aeEltiOWbj9rymVZopMAWXn5XSXEtTSbC38wC4eVcR78X8qSdpDgsmnbJ1f+N54DTVot9RzvlM/ootRmv9ohQyvtQA=
  - secure: YmV1ycxfoRHZ+mh2PVew7Yrcq1/XGX4n4VRJbuhZPijO60e2aAy/GvRQVJYg2urUd8S6yNd2P7B0KcFX5OvFeJlGSjqgI1WcIdGtEA8RhLKXmJn3awG4CHsjHSbSnKH0EsrYTWCPcWh2KYv9GrZYBLO0VA09b7s/M2RF802YZlUWIyqm8wmdbAsrjxytdvlqJSh4q9GrvW9iGnKZIjqdn05rnPehZj7OHk2Aj3esfquYd+LRkT+NxXyAnP4h38G+LCV01w2SvhUBQj/czPtZ+v4BD8LnzCoTGYUDMHR9tGnWhRn2ABJ/SMonmu6asoIZra5tRmdRD3/yDrTXEtwP7TCK8t1bOVVgbTjbh7sCmGdtNmSpijF9NDiz5WwZGajgDeyzDctbk+w5AzDvY1tkPIVa66bk8whQ5ZAqp/DZDsBQATdWp3cT6rkXsvp9rdY3L64nnT0VGK0Wi+FPl3NWJOe9PtobiO76aTW0Kl7NOkgE/iGi8EsUebFpS1tm27nl1PgnzGqJEqAE+wAOXE3k0nGMNZ3Ia3zfuWoAWr7zCRpZRx3pNtOEG94syqZDHnRPa5gCkH2r05JK9Bi7zQhSwNc8HXY9Cz6hQM89dxIEyUf7YBD+mkwnhH8E877EhQqMcpEoXkpBPp7QYjfsAeVBWXowHhODjM8Rzq5/zZK+ReI=
