sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
install: ''
before_script: ./.travis_release.sh
script:
- sbt publish
env:
  global:
  - secure: SQvKd25Q5LANSaLiDrsZtX8RNc109eOFYpIXblEf3VJN+48g2liYU2PG6a44s+O8qdhFX8bqGhuNyJaV9vS3SJNmawNYjBZtvtGS4UpJmCBWGjTBzPMybRqkBXYBJ2XNmp+TPaHbGRbFFPkvui9Z6R3AdyeOpVejZVwPPZfYWnX9SdxQ0jgD2qM2WavWRz/2t3XhBiOqsbfziwe68vWqnWXozDk8K8JAoBc4/nL/XokD0QYaBgMzaOrHYOTUhiIzORsupU+51IyTnLBcBN99BzMlK+Hy0Vx/euUO3X2C3ehERBy+ex5tBg1oCwKbKbFyAEcqv83i3MVM9fAcNp6Bu/9FchFfvT+4Lt4tvAOS4kcKnSRCu5rBS1fv8AxcoJMuLKG4gOMsra69Wp4taMBOIlz9fNCTBtXwCeLojthpifyfNyd/xjK+ci7j136ihbeAqcn8GaUNUMU0Riim1miRQM9CDRi3V1i5NUu1epwmoMZ3NlAfjFo3WKoSOiK2gbhxS3Co4SW1wJONu20yD+1lLWa/3wKbxj9JBcGWEF77Didvf7tQ3i5/z7pgioC99xrtnpoAF/obICih1XjVUqt89D2MaFBE/vl2MDO14b7MlirjmZ1p1hoVQu9/ynLDDLLL3DRUAx9ptawRgljNlla3uM+Df8Mp7BpS6tTUGgjoGq8=
  - secure: FkWs35GsLroZem+zUloxirw+dKA32GgGy7jj609xv9N4Q6TZGGfJ4UX8bkSfvUCuqLJ0+y9+8JKb1zueSm/wdOwVul3+uz7I16GJfnWws0PO62tUH76XEkLQezsa8P88QKICSYtAUh1BLtB3oJqRQRjPzvzrJAAI5sRh9wa4ynDF6RBAgeV6z8RY7SYsFlYfTj4Ho8Aly0HEy1SDikHTC4XiXS9x6SofZSh3UJCajL1fEbwinjMXUT6Q47Dr5SN7KAbG0fHlEfAtYXVGd9vw5APxyqdzM43Hng8WlhPbMHin96mzVY6ZgmtYqIsxrc5m2vjnKyn0GFpF1o+bhIKIVUAhiyiJfpm1shV7RH7BmAesGTkLRGAYxYInZJEfhcxtGqG7Zp8/ntPLvcxgFZzKz36P0b218OMVH49jzCVRzQO13/TNGA83OiyTK1kRbSFguV4FPfksZx/2Fu+ddQFpcguetkok+XYLIZx5ggrog3njW4bQqrN7NJZWhXBB1UVnuAqDA8W+CDhNLPapEEW3H9vDY/YmjkZYKMVx/yCv1vm4vg2aMmpFzasFoyq6A6KokA2RkIReSLDtTzFZ303CtsylsZTa6CBBySTW/g3o9njjIUA4dOWNoQ0ltuVCZTEOG0cX5vO0ylrdxjP3iN1EWhtnA+vdeYT3GfYMcYgPSUw=
